### ISSUE TITLE
Issue when importing in python 3.7

### ISSUE THREAD

**Issue by MicahStevens** [norcuni/zipencrypt#1]
thanks for this! 
When using in python 3.7, on import I get:  

```
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipencrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/zipencrypt/__init__.py", line 12, in <module>
    from .zipencrypt3 import ZipFile, is_zipfile, ZipInfo
  File "/usr/lib/python3.7/site-packages/zipencrypt/zipencrypt3.py", line 359, in <module>
    class _ZipEncrypter(_ZipDecrypter):
TypeError: function() argument 1 must be code, not str
```
Fortunately my target system is 3.5, so a non-issue for me currently, but was initially testing on my laptop which is 3.7..

**Comment by devthat** [comment]
Thanks for your feedback:) Should be fixed now.
